Document: longbranch-repos
Title: Debian longbranch-repos Manual
Author: <insert document author here>
Abstract: This manual describes what longbranch-repos is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/longbranch-repos/longbranch-repos.sgml.gz

Format: postscript
Files: /usr/share/doc/longbranch-repos/longbranch-repos.ps.gz

Format: text
Files: /usr/share/doc/longbranch-repos/longbranch-repos.text.gz

Format: HTML
Index: /usr/share/doc/longbranch-repos/html/index.html
Files: /usr/share/doc/longbranch-repos/html/*.html

  
